# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.10.4

      - name: Install dependencies
        run: flutter pub get

      - name: Install cider
        run: dart pub global activate cider

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Update version
        run: cider bump build

      - name: Git config email
        run: git config --global user.email "you@example.com"

      - name: Git config name
        run: git config --global user.name "Your Name"

      - name: Git fetch 1
        run: 
          git fetch

      - name: Git status
        run: 
          git status
      - name: Git add
        run: 
          git add .
      - name: Git commit
        run: 
          git commit -m "Build number bump"
      
      - name: Git fetch 2
        run: 
          git fetch

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          force: false